### ISSUE TITLE
Add back custom operators

### ISSUE THREAD

**Issue by disnet** [sweet-js/sweet.js#517]
Pre 1.0 had the ability to define custom operators with precedence and associativity. It would be nice to have that back. Some syntax ideas:

``` js
operator ** 14 right = function (left, right) {
  return #`Math.pow(${left}, ${right})`;
}
```

Most of the plumbing for this features is already done. Just need to decide on the right syntax.

**Comment by vendethiel** [comment]
How to define unary operators with this syntax?

**Comment by gabejohnson** [comment]
@disnet are you thinking of hard-coding this into the enforester/macro-context or implementing it as a macro? It seems like operators and infix macros require some of the same features (access to a prefix of tokens).

**Comment by GuillaumeLeclerc** [comment]
This is a very important feature in my opinion. It would be good to have it

**Comment by dmitriz** [comment]
@disnet That sounds like very useful feature. Are there any reference to the old version supporting it or other projects?

**Comment by disnet** [comment]
@dmitriz Sure, the old documentation is available at http://sweetjs.org/doc/main/sweet.html

**Comment by gabejohnson** [comment]
@disnet I just got another question about this on Gitter. Do you want to have a design discussion about it?

**Comment by disnet** [comment]
@gabejohnson absolutely, do you have some design ideas kicking around? I haven't had the chance to think about it deeply in a while.

**Comment by mooreniemi** [comment]
Looks like this has been hanging out for about a year now. Anything I can do to help it land?

**Comment by disnet** [comment]
@mooreniemi if you'd like to dive in that would be awesome! Nothing has been blocking it, just not on top of my stack. 

There should be two pieces to getting this landed. One is the syntax design and the other is wiring it up. 

For wiring it up you need to:

* make the enforester recognize the new special form (like how it currently does with `syntax`)
* add the operator definition to the compile time environment (similar to [here](https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/token-expander.js#L209-L231))
* look in the environment when enforesting operators for any custom definitions (should be happening [here](https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/enforester.js#L1819-L1852)
* and then using the custom definition, essentially do a macro expansion instead of `combine`

For the syntax design it sounded like @gabejohnson had some ideas?

**Comment by gabejohnson** [comment]
@mooreniemi Any help would be welcome!

As far as design goes, I want to make sure we don't introduce new primitive forms unnecessarily. And I can't shake the feeling that this *has* to tie in to infix operators.

I know operators are some of the more complex forms to parse, but if we exposed `Enforester#opCtx` in `MacroContext`. I think we could do this by making an `operator` macro.
```js
operator foo (left, right, associativity='left', precedence=13) {
  // left is already enforested at this point as it will be with infix macros
  return #`${op}(${left}, ${right.expand('Expression')})`;
}
```
The operator context stack juggling could be done in the definition of the `operator` macro. `associativity` and `precedence` in the above don't even have to be used in the defined transform function. They can just be plucked out by the macro definition.

There would be a lot of duplicate code b/w the macro and the enforester unless we were able to leverage the enforester or have all operators dispatch to the macro. See the bottom of this https://github.com/sweet-js/sweet.js/issues/516#issuecomment-273511542. Though that might slow things down too much.

As to defining something like:
```js
operator |> (...) {
  ...
}
```
It would be my preference starting out just defining the new punctuator w/ readtables. The only other reasonable way to do it, to my mind, would be to have the whole pipeline be lazy and extend the readtable in the `operator` macro.

Whatever happens @disnet, I think getting infix macros done first makes the most sense as I think they're a superset of all other syntactic extensions.

**Comment by disnet** [comment]
@gabejohnson so I started writing a long post saying why I thought that wouldn't work but then realized it actually kinda would and that it's super easy to add infix macros. So #643.

I'm still not entirely sure I'm comfortable with exposing `opCtx` to macros. I much prefer keeping internals internal so as to maintain invariants. Also speed, as you noted making every operator a macro invocation is probably not great. My guess is that having a custom operator special form is the best approach.

But we can totally experiment.

**Comment by gabejohnson** [comment]
@disnet I don't want to beat a dead horse here but I'd still want like to avoid creating a single purpose special form (if possible).

Consider this:
```js
syntax m: { precedence: 13, associativity: 'left' } = ctx => {
  ...
}
```

This syntax would put additional information on the `BindingIdentifier` that will get passed to the `CompiletimeTransform` instance. This information would be used during enforestation to determine whether we're entering into or remaining in the operator parsing machinery.

I realized that in my example above...
```js
operator foo (left, right, associativity='left', precedence=13) {
  // left is already enforested at this point as it will be with infix macros
  return #`${op}(${left}, ${right.expand('Expression')})`;
}
```
...that conflating local, runtime binding syntax w/ what were essentially compile-time bindings was misguided. But there is already precedent (Flow, TypeScript) for my latest proposal.

A side benefit is that this syntax could be adapted in the future for type hints if we so desire (in this case type a parameterized one, `Operator(13, left)`). To make that useful for the user, however, we would need to attach this data to `BindingIdentifier`s whenever it is encountered. Then we strip it out during term reduction.

It might make sense to do this work at the same time that we implement your proposal in #620 (if we go forward with that).

**Comment by disnet** [comment]
I'll have to stew on it for a while but I think I like your proposed syntax.

We could also throw in a `#` somewhere to signal "syntax things are happening":

```js
syntax m: #{ precedence: 13, associativity: 'left' } = ctx => {
  ...
}
```

**Comment by gabejohnson** [comment]
We could do that, but I don't think it adds any information that isn't already provided by `syntax`. Unless you mean to signal the enforester.
