### ISSUE TITLE
Move repo to the sweet-js organization

### ISSUE THREAD

**Issue by disnet** [sweet-js/sweet.js#528]
Since Sweet doesn’t have much attachment to Mozilla anymore, I’m thinking of transferring the sweet.js repo to the [sweet-js](https://github.com/sweet-js) organization.

Does anyone have strong opinions or warnings about the transfer process? My understanding is github sets up nice redirects and everything but are there any gotchas people know about?

**Comment by francescoagati** [comment]
+1
