### ISSUE TITLE
sjs tool not creating sourcemap file on compile.

### ISSUE THREAD

**Issue by afaur** [sweet-js/sweet.js#555]
I have tried using the `--sourcemap` argument discussed here https://github.com/sweet-js/sweet.js/issues/13 and can't seem to get it to work.  

I tried modifiying the `sjs` file in my `node_modules/.bin/` to always include true for the sourceMap option, thinking that it was not passing the argument and that still failed.

I looked at this for guidence: https://github.com/sweet-js/sweet.js/blob/29da35c04cb23af57105f702b84c434b116b06f9/doc/main/sweet.md#sweetcompile

I added the line right above this line: https://github.com/sweet-js/sweet.js/blob/2da62fd7cc41187b241a6b8e8c417c48fff20f02/bin/sjs#L34

This still did not work, and I am thinking that maybe I just don't understand how it works well enough.

I have a test project setup here that you can use to recreate the issue: https://github.com/afaur/node-sweet-basic

This is where I am calling the sjs command in the project: https://github.com/afaur/node-sweet-basic/blob/master/bin/build#L21

Thanks for any help you can provide on this.

**Comment by disnet** [comment]
Sourcemaps didn't make it into the 1.0 redesign. Tracking adding them back with #513.
