### ISSUE TITLE
Macros that return empty syntax lists throw errors

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet.js#561]
If a macro that returns an empty syntax list is referenced an error is thrown:

``` js
syntax m = ctx => {
  return ctx;
};

// throws "TypeError: Cannot read property 'toString' of undefined"
m;

(m); // throws "Error: unexpected syntax m"
[m]; // throws "Error: expected expression"

```

**Comment by disnet** [comment]
I can confirm that `(m)` and `[m]` are incorrectly throwing errors but bare `m` seems to work just fine for me on master.

**Comment by gabejohnson** [comment]
My bad. It was throwing with no semicolon after:
```js
syntax m = ctx => {
  return ctx;
};

m // no semicolon
```

**Comment by gabejohnson** [comment]
I've been looking into this as I think I've found the offending code:

https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/enforester.js#L1078
https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/enforester.js#L364

The problem is that `lookahead === undefined`. In the case of a statement we can return `EmptyStatement`. But in the case of an expression this fails here:

https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/term-expander.js#L430

and here

https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/enforester.js#L1559

This shouldn't error if we were just in a macro expansion.

**Comment by gabejohnson** [comment]
I think `(m)` should throw a syntax error in this case. Empty parenthesized expressions are disallowed.

That just leaves `[m]`. Under what circumstances is it an error for `enf.enforestExpressionLoop()` to evaluate to `null` [here](https://github.com/sweet-js/sweet.js/blob/1ff70369885b567ca9c6f04933974ca53c48e70d/src/enforester.js#L1559)?

**Comment by disnet** [comment]
Oh good points. I suspect we could remove the `null` check in `enforestArrayExpression`. I can't think of a cases where null should be disallowed there.
