### ISSUE TITLE
Multiple issues with modules

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet.js#562]
I'm having trouble importing for syntax:

``` js
// a.js
#lang "sweet.js"
let a;
if(true) {
  a = 1;
}
export default a;


// m.js
#lang "sweet.js"
import a from './a' for syntax;

syntax m = ctx => #`1`;
m 1;
```

This throws `ReferenceError: a is not defined`. I think it has something to do with block statements as referencing `a` inside a function is fine as long as it's not within a block statement.

Just importing the module for side-effects has it's own problems:

``` js
// m.js
#lang "sweet.js"
import './a' for syntax; // importing nothing

syntax m = ctx => #`1`;
m 1;
// "Error: expecting parens"
```

Altering the arrow function syntax slightly:

``` js
// m.js
#lang "sweet.js"
import './a' for syntax; // importing nothing

syntax m = ctx => {
  return #`1`;
};
m 1;
// "Error: [assertion error]: cannot get the val of a delimiter"
```

**Comment by disnet** [comment]
Yeah, the modules handling code is a bit alpha quality right now. My current focus is cleaning it up.

**Comment by gabejohnson** [comment]
Good news. This works for default exports/imports (aside from ASI and reader dispatch quirks):
```javascript
// a.js
#lang "sweet.js"
let a;
if(true) {
  a = 1;
}
export default a;

// m.js
#lang "sweet.js"
import a from './a' for syntax;

syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`${dummy.fromNumber(a)}`
};
m;

// "sweet.js";
// ;
// ;
// 1;
```
The `"sweet.js"` artifact will be there until we wire up languages. I thought there was a bug for ASI stuff but I can't find it right now.

**Comment by disnet** [comment]
Closing, I think all module work can now be traced in #620 and #633.
