### ISSUE TITLE
Enforester::createError assumes everything is a term

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet.js#572]
On the gitter channel we were trying to debug a problem (turned out to be object literals vs. labeled statements in blocks). Here's a link to the error:

https://gitter.im/sweet-js/sweet.js?at=57b12ac1a00c6adb45e6dff3

I'm guessing a `safeCheck` should fix it, but I don't have time to try it right now. I may submit a PR later this week.

**Comment by disnet** [comment]
Yeah, looks like `safeCheck` should do it.
