### ISSUE TITLE
Not a valid expression 

### ISSUE THREAD

**Issue by WreckedAvent** [sweet-js/sweet.js#580]
Context:

I am making a general `ap` macro for working with [applicative functors](http://learnyouahaskell.com/functors-applicative-functors-and-monoids). The syntax gain is marginal here, but I was using it as an exercise. 

``` javascript
syntax ap = function(ctx) {
    let ident = ctx.next().value
    let result = #`${ident}`

    for (let stx of ctx) {
      result = result.concat(#`.ap(${stx})`)
    }

    return result
}

ap add 2 4
```

Works as expected (`add.ap(2).ap(4)`).

However, 

``` javascript
ap Promise.lift(add) 2 4
```

Does not. Rightfully perhaps, since I now need expressions instead of just singular tokens.

My instinct was to expand it like this:

``` javascript
syntax ap = function(ctx) {
    let ident = ctx.expand('expr').value
    let result = #`${ident}`

    for (let stx of ctx) {
      result = result.concat(#`.ap(${stx})`)
    }

    return result
}

ap Promise.lift(add) 2 4
```

Expected:

``` javascript
Promise.lift(add).ap(2).ap(4)
```

Actual:

>  Error: not a valid expression
> __.__ ap 2 . ap 5

**Comment by gabejohnson** [comment]
This works as expected now. Can we close?

**Comment by disnet** [comment]
Should work now.
