### ISSUE TITLE
Garbage output when missing semi colon

### ISSUE THREAD

**Issue by davidson16807** [sweet-js/sweet.js#591]
I love the idea for sweet.js. I made a [macro](https://github.com/davidson16807/sweet-tensors) to help out some work I've been doing with scalar fields. [Here](http://sweetjs.org/browser/editor.html#%0A%0Asyntax%20tensor%20=%20%28%20function%28%29%20%7B%0A%0A%20%20let%20length_lookup%20=%20%7B%20%0A%20%20%20%20a:#%60la%60,%20b:#%60lb%60,%20c:#%60lc%60,%20d:#%60ld%60,%20e:#%60le%60,%20f:#%60lf%60,%20g:#%60lg%60,%20h:#%60lh%60,%20i:#%60li%60,%20%0A%20%20%20%20j:#%60lj%60,%20k:#%60lk%60,%20l:#%60ll%60,%20m:#%60lm%60,%20n:#%60ln%60,%20o:#%60lo%60,%20p:#%60lp%60,%20q:#%60lq%60,%20r:#%60lr%60,%20%0A%20%20%20%20s:#%60ls%60,%20t:#%60lt%60,%20u:#%60lu%60,%20v:#%60lv%60,%20w:#%60lw%60,%20x:#%60lx%60,%20y:#%60ly%60,%20z:#%60lz%60,%20%0A%20%20%7D;%0A%20%20let%20temp_variables%20=%20%5B%0A%20%20%20%20#%60$a%60,%20#%60$b%60,%20#%60$c%60,%20#%60$d%60,%20#%60$e%60,%20#%60$f%60,%20#%60$g%60,%20#%60$h%60,%20#%60$i%60,%20%0A%20%20%20%20#%60$j%60,%20#%60$k%60,%20#%60$l%60,%20#%60$m%60,%20#%60$n%60,%20#%60$o%60,%20#%60$p%60,%20#%60$q%60,%20#%60$r%60,%20%0A%20%20%20%20#%60$s%60,%20#%60$t%60,%20#%60$u%60,%20#%60$v%60,%20#%60$w%60,%20#%60$x%60,%20#%60$y%60,%20#%60$z%60,%20%0A%20%20%5D%0A%20%20let%20operators%20=%20%5B'+','-','*','/',',','.','&','%7C','%25','&&','%7C%7C'%5D;%0A%0A%20%20//%20check%20for%20any%20token%20that%20can%20belong%20to%20an%20indexible%20expression%0A%20%20//%20an%20indexible%20expression%20is%20for%20instance%20%22this.foo%5Bi%5D.getBar%28%29%5Bj%5D%22%0A%20%20let%20isIndexible%20=%20function%28token%29%20%7B%0A%20%20%20%20return%20%20token.isBrackets%28%29%20%7C%7C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20token.isParens%28%29%20%7C%7C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20token.isIdentifier%28%29%20%7C%7C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20token.val%28%29%20===%20'.';%0A%20%20%7D%0A%0A%20%20let%20isTensorIndex%20=%20function%28token,%20subtokens%29%20%7B%0A%20%20%20%20return%20%20token.isBrackets%28%29%20&&%0A%20%20%20%20%20%20%20%20%20%20%20%20subtokens.length%20===%201%20&&%20%0A%20%20%20%20%20%20%20%20%20%20%20%20length_lookup%5Bsubtokens%5B0%5D.val%28%29%5D%20!==%20void%200;%0A%20%20%7D%0A%0A%20%20//%20returns%20all%20tokens%20to%20the%20end%20of%20the%20file%20or%20block,%20whichever%20comes%20first%0A%20%20let%20tokenize%20=%20function%28ctx%29%20%7B%0A%20%20%20%20let%20tokens%20=%20%5B%5D;%0A%20%20%20%20let%20token;%0A%20%20%20%20while%28token%20=%20ctx.next%28%29.value%29%7B%0A%20%20%20%20%20%20tokens.push%28token%29%0A%20%20%20%20%7D%0A%20%20%20%20ctx.reset%28%29;%0A%20%20%20%20return%20tokens;%0A%20%20%7D%0A%0A%20%20let%20parse_statement%20=%20function%28tokens,%20pos%29%7B%0A%20%20%20%20let%20binary%20=%20%5B'.','+','-','/','*','%25','%3C','%3E','&','%7C','%5E','&&','%7C%7C','~','%3C%3C','%3E%3E','%3E%3E%3E'%5D;%0A%20%20%20%20let%20unary%20=%20%5B'++',%20'--'%5D;%0A%20%20%20%20let%20statement%20=%20%5B%5D;%0A%0A%20%20%20%20let%20token,%20prev_token;%0A%20%20%20%20let%20line,%20prev_line;%0A%20%20%20%20for%20%28let%20i%20=%20pos;%20i%20%3C%20tokens.length;%20i++%29%20%7B%0A%20%20%20%20%20%20token%20=%20tokens%5Bi%5D;%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20line%20=%20token.lineNumber%28%29;%0A%0A%20%20%20%20%20%20if%20%28line%20!==%20prev_line%20&&%20%0A%20%20%20%20%20%20%20%20%20%20prev_line%20!==%20void%200%20&&%0A%20%20%20%20%20%20%20%20%20!token.isDelimiter%28%29%20&&%20%0A%20%20%20%20%20%20%20%20%20%20binary.indexOf%28token.val%28%29%29%20===%20-1%20&&%20%0A%20%20%20%20%20%20%20%20%20%20binary.indexOf%28prev_token.val%28%29%29%20===%20-1%20&&%20%0A%20%20%20%20%20%20%20%20%20%20unary.indexOf%28prev_token.val%28%29%29%20===%20-1%29%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20break;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20prev_line%20%20=%20line;%0A%20%20%20%20%20%20prev_token%20=%20token;%0A%20%20%20%20%20%20statement.push%28token%29;%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if%28token.val%28%29%20===%20';'%29%20break;%0A%20%20%20%20%7D%0A%20%20%20%20return%20statement;%0A%20%20%7D%20//%20end%20parse_statement%28%29%0A%0A%20%20//%20returns%20all%20tokens%20to%20the%20end%20of%20the%20file%20or%20block,%20whichever%20comes%20first%0A%20%20let%20parse_statements%20=%20function%28tokens%29%20%7B%0A%20%20%20%20let%20statements%20=%20%5B%5D;%0A%20%20%20%20for%20%28let%20i=0;%20i%20%3C%20tokens.length;%20%29%20%7B%0A%20%20%20%20%20%20let%20statement%20=%20parse_statement%28tokens,%20i%29;%0A%20%20%20%20%20%20statements.push%28statements%29;%0A%20%20%20%20%20%20i%20+=%20statement.length;%0A%20%20%20%20%7D%0A%20%20%20%20return%20statements;%0A%20%20%7D%0A%0A%20%20let%20consume_tokens%20=%20function%28ctx,%20tokens%29%7B%0A%20%20%20%20let%20token;%0A%20%20%20%20for%20%28var%20i%20=%200;%20i%20%3C%20tokens.length;%20i++%29%20%7B%0A%20%20%20%20%20%20if%28!ctx.next%28%29%29%20%7B%0A%20%20%20%20%20%20%20%20break;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%0A%20%20let%20tokens_hash%20=%20function%28tokens%29%20%7B%0A%20%20%20%20return%20tokens.map%28token%20=%3E%20token.val%28%29%29.join%28''%29;%0A%20%20%7D%0A%20%20let%20multidict%20=%20%7B%0A%20%20%20%20add:%20function%28multidict,%20key,%20added%29%20%7B%0A%20%20%20%20%20%20multidict%5Bkey%5D%20=%20multidict%5Bkey%5D%20%7C%7C%20%5B%5D;%0A%20%20%20%20%20%20multidict%5Bkey%5D.push%28added%29;%0A%20%20%20%20%7D,%0A%20%20%20%20values:%20function%28multidict_%29%20%7B%0A%20%20%20%20%20%20let%20nested_values%20=%20%5B%5D;%0A%20%20%20%20%20%20let%20multidict_keys%20=%20Object.keys%28multidict_%29.slice%280%29;%0A%20%20%20%20%20%20for%28let%20key%20of%20multidict_keys%29%7B%0A%20%20%20%20%20%20%20%20nested_values.push%28multidict_%5Bkey%5D%29;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20%5B%5D.concat.apply%28%5B%5D,%20nested_values%29;%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20let%20multiset%20=%20%7B%0A%20%20%20%20add:%20function%28multiset,%20added%29%20%7B%0A%20%20%20%20%20%20multiset%5Badded%5D%20=%20multiset%5Badded%5D%20%7C%7C%200;%0A%20%20%20%20%20%20multiset%5Badded%5D++;%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20let%20TokenArray%20=%20%7B%7D;%0A%20%20TokenArray.indexOf%20=%20function%20%28match,%20tokens,%20from_index%29%20%7B%0A%20%20%20%20%20%20let%20li%20=%20tokens.length%20+%201%20-%20match.length;%0A%20%20%20%20%20%20let%20jl%20=%20match.length;%0A%20%20%20%20%20%20loop:%20for%20%28let%20i%20=%20from_index%20%3E%3E%3E%200;%20i%3Cli;%20i++%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20for%20%28let%20j=0;%20j%3Cjl;%20j++%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20%28tokens%5Bi+j%5D%20!==%20match%5Bj%5D%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20continue%20loop;%0A%20%20%20%20%20%20%20%20%20%20return%20i;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20-1;%0A%20%20%7D%0A%20%20TokenArray.replace%20=%20function%20%28replaced,%20replacement,%20within%29%20%7B%0A%20%20%20%20let%20index%20=%200;%0A%20%20%20%20let%20i%20=%200;%0A%0A%20%20%20%20return%20tokens;%0A%20%20%7D%0A%20%20let%20get_indices%20=%20function%28tokens,%20indices,%20indices_to_arrays,%20array_counts%29%20%7B%0A%20%20%20%20if%28indices%20===%20void%200%29%20%20%20%20%20%20%20%20%20%20%20indices%20=%20%7B%7D;%0A%20%20%20%20if%28indices_to_arrays%20===%20void%200%29%20indices_to_arrays%20=%20%7B%7D;%0A%20%20%20%20if%28array_counts%20===%20void%200%29%20%20%20%20%20%20array_counts%20=%20%7B%7D;%0A%0A%20%20%20%20let%20subtokens%20=%20%5B%5D;%0A%20%20%20%20let%20last_indexible%20=%20%5B%5D;%0A%0A%20%20%20%20for%20%28var%20i%20=%200;%20i%20%3C%20tokens.length;%20i++%29%20%7B%0A%20%20%20%20%20%20let%20token%20=%20tokens%5Bi%5D;%0A%0A%20%20%20%20%20%20if%20%28token.isDelimiter%28%29%29%7B%0A%20%20%20%20%20%20%20%20subtokens%20=%20tokenize%28token.inner%28%29%29;%0A%20%20%20%20%20%20%20%20get_indices%28subtokens,%20indices,%20indices_to_arrays,%20array_counts%29;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20//%20check%20for%20tensor%20index%20within%20%5B%5D%0A%20%20%20%20%20%20if%20%28isTensorIndex%28token,%20subtokens%29%29%7B%0A%20%20%20%20%20%20%20%20%20%20let%20index%20=%20subtokens%5B0%5D;%0A%20%20%20%20%20%20%20%20%20%20indices%5Bindex.val%28%29%5D%20=%20index;%0A%20%20%20%20%20%20%20%20%20%20multidict.add%28indices_to_arrays,%20index.val%28%29,%20last_indexible.slice%280%29%29;%0A%20%20%20%20%20%20%20%20%20%20multiset.add%28array_counts,%20tokens_hash%28last_indexible%29%29;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20//%20compile%20a%20list%20of%20array%20values%20formed%20over%20multiple%20tokens,%0A%20%20%20%20%20%20//%20%20e.g.%20this.foo%5Bi%5D.getBar%28%29%5Bj%5D%0A%20%20%20%20%20%20if%20%28isIndexible%28token%29%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20last_indexible.push%28token%29;%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20last_indexible%20=%20%5B%5D;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20Object.keys%28indices%29;%0A%20%20%7D%0A%0A%20%20let%20is_array_independant%20=%20function%28array%29%20%7B%0A%20%20%20%20return%20get_indices%28array%29.length%20===%200;%0A%20%20%7D%0A%20%20let%20is_array_dependant_on_index%20=%20function%28array,%20i%29%20%7B%0A%20%20%20%20return%20get_indices%28array%29.includes%28i%29;%0A%20%20%7D%0A%20%20let%20is_array_dependant_on_indices%20=%20function%28array,%20indices%29%20%7B%0A%20%20%20%20return%20indices.some%28i%20=%3E%20get_indices%28array%29.includes%28i%29%29;%0A%20%20%7D%0A%20%20let%20is_index_independant%20=%20function%28i,%20indices_to_arrays%29%20%7B%0A%20%20%20%20return%20indices_to_arrays%5Bi%5D.some%28is_array_independant%29;%0A%20%20%7D%0A%20%20let%20is_index_dependant_on_index%20=%20function%28i,%20j,%20indices_to_arrays%29%20%7B%0A%20%20%20%20return%20indices_to_arrays%5Bi%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20.some%28array%20=%3E%20%20is_array_dependant_on_index%28array,%20j%29%29;%0A%20%20%7D%0A%20%20let%20is_index_dependant_on_indices%20=%20function%28i,%20indices,%20indices_to_arrays%29%20%7B%0A%20%20%20%20return%20indices_to_arrays%5Bi%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20.some%28array%20=%3E%20%20is_array_dependant_on_indices%28array,%20indices%29%29;%0A%20%20%7D%0A%20%20let%20is_array_reevaluated%20=%20function%28array%29%20%7B%0A%20%20%20%20if%20%28array.length%20%3E%201%29%20%7B%0A%20%20%20%20%20%20return%20true;%0A%20%20%20%20%7D%0A%20%20%20%20return%20false;%0A%20%20%7D%0A%0A%20%20return%20function%20%28ctx%29%20%7B%0A%20%20%20%20let%20indices%20=%20%7B%7D;%0A%20%20%20%20let%20indices_to_arrays%20=%20%7B%7D;%0A%20%20%20%20let%20array_counts%20=%20%7B%7D;%0A%0A%20%20%20%20let%20tokens%20=%20tokenize%28ctx%29;%0A%20%20%20%20let%20consumed;%0A%20%20%20%20if%28tokens%5B0%5D.isBraces%28%29%29%7B%0A%20%20%20%20%20%20consumed%20=%20%5Btokens%5B0%5D%5D;%0A%20%20%20%20%20%20tokens%20=%20tokenize%28tokens%5B0%5D.inner%28%29%29;%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20tokens%20=%20parse_statement%28%20tokens,%200%20%29;%0A%20%20%20%20%20%20consumed%20=%20tokens;%0A%20%20%20%20%7D%0A%0A%20%20%20%20consume_tokens%28ctx,%20consumed%29;%0A%0A%20%20%20%20get_indices%28tokens,%20indices,%20indices_to_arrays,%20array_counts%29;%0A%0A%0A%20%20%20%20//%20Wrap%20the%20block%20of%20code%20in%20a%20for%20loop%0A%0A%20%20%20%20let%20loop%20=%20#%60$%7Btokens%7D%60;%0A%20%20%20%20let%20index_strs%20=%20Object.keys%28indices%29.slice%280%29;%0A%0A%20%20%20%20//%20determine%20the%20order%20needed%20to%20nest%20the%20loops%20%0A%20%20%20%20//%20order%20is%20determined%20based%20upon%20dependency%0A%20%20%20%20let%20independant_indices%20=%20index_strs%0A%20%20%20%20%20%20.filter%28%20i%20=%3E%20indices_to_arrays%5Bi%5D.some%28is_array_independant%29%20%29;%0A%20%20%20%20let%20index_strs_sorted%20=%20independant_indices;%20%20%0A%20%20%20%20let%20remaining_indices%20=%20index_strs%0A%20%20%20%20%20%20.filter%28%20i%20=%3E%20independant_indices.indexOf%28i%29%20===%20-1%20%29;%0A%0A%20%20%20%20while%20%28remaining_indices.length%20%3E%200%29%20%7B%0A%20%20%20%20%20%20let%20dependant_indices%20=%20remaining_indices%0A%20%20%20%20%20%20%20%20.filter%28%20i%20=%3E%20indices_to_arrays%5Bi%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.some%28array%20=%3E%20%20is_array_dependant_on_indices%28array,%20index_strs_sorted%29%20&&%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20!is_array_dependant_on_indices%28array,%20remaining_indices%29%20%29%20%20%29;%0A%20%20%20%20%20%20remaining_indices%20=%20remaining_indices%0A%20%20%20%20%20%20%20%20.filter%28%20i%20=%3E%20!dependant_indices.includes%28i%29%20%29;%0A%20%20%20%20%20%20index_strs_sorted%20=%20%5B%5D.concat%28dependant_indices,%20index_strs_sorted%29;%0A%20%20%20%20%7D%20;%0A%0A%20%20%20%20for%20%28let%20index_str%20of%20index_strs_sorted%29%7B%0A%20%20%20%20%20%20let%20index%20=%20indices%5Bindex_str%5D;%0A%20%20%20%20%20%20let%20length%20=%20length_lookup%5Bindex_str%5D;%0A%20%20%20%20%20%20let%20arrays%20=%20indices_to_arrays%5Bindex_str%5D;%0A%0A%20%20%20%20%20%20//%20don't%20refer%20arrays%20with%20indices%20if%20you%20can%20help%20it%0A%20%20%20%20%20%20let%20arrays_sans_indices%20=%20arrays.filter%28is_array_independant%29;%0A%20%20%20%20%20%20if%20%28arrays_sans_indices.length%20%3E%200%29%20arrays%20=%20arrays_sans_indices;%0A%0A%20%20%20%20%20%20let%20array%20=%20arrays.sort%28%28a,b%29%20=%3E%20a.length%20-%20b.length%29%5B0%5D;%0A%0A%20%20%20%20%20%20loop%20=%20#%60for%28var%20$%7Bindex%7D=0,%20$%7Blength%7D=$%7Barray%7D.length;%20$%7Bindex%7D%20%3C%20$%7Blength%7D;%20$%7Bindex%7D++%29%20%7B%20$%7Bloop%7D%20%7D%60;%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20return%20loop;%0A%20%20%20%20//%20return%20#%60boo%60;%0A%20%20%7D%0A%7D%29%28%29;%0A%0A%0AScalarField.add_field%20=%20function%28field1,%20field2,%20result%29%20%7B%0A%20%20result%20=%20result%20%7C%7C%20new%20Float32Array%28field1.length%29;%0A%0A%20%20tensor%20result%5Bi%5D%20=%20field1%5Bi%5D%20+%20field2%5Bi%5D;%0A%0A%20%20return%20result;%0A%7D;) is a live demo when its working.

However, I noticed sweet.js has some really weird behavior when you forget a semi-colon. When I forget the first semi-colon in the example above: 

```
ScalarField.add_field = function(field1, field2, result) {
    result = result || new Float32Array(field1.length)

    tensor result[i] = field1[i] + field2[i];

    return result;
};
```

It should output something like the following:

```
ScalarField.add_field = function (field1_3592, field2_3593, result_3594) {
  result_3594 = result_3594 || new Float32Array(field1_3592.length);
  for (var i = 0, li = result_3594.length; i < li; i++) {
    result_3594[i] = field1_3592[i] + field2_3593[i];
  }
  return result_3594;
};
```

Instead, sweet.js outputs the following:

```
ScalarField.add_field = function (field1_104, field2_105, result_106) {
  result_106 = result_106 || (result_106[i] = field1_104[i] + field2_105[i]);
  return result_106;
};
```

`new Float32Array()` is obliterated and now the output is nowhere close to making sense. It took me a long while to realize the semi-colon was at fault.

This makes me have serious misgivings about using sweet.js. I want to use sweet.js because I think it can eliminate the opportunity for bugs in a bunch of long winded code. But now, if I forget a single semi-colon, even one that javascript wouldn't need to produce correct output, it's going to silently generate garbage code and its going to be very hard to track down the problem.

There needs to be some way to handle missing semi-colons. This could be done through a warning, an error, or even a reimplementation of javascript's automatic semi-colon insertion, full or partial.

**Comment by disnet** [comment]
This is a bug, Sweet normally handles ASI just fine (or as fine as you can with literally the worst feature of JavaScript).

Here's a related minimal repro:

```js
syntax m = ctx => {
    return #`1`
}

result = result || f()
m
```

This actually throws an error rather than consuming input but it's probably related. I think it has to do with our handling of calls because replacing `f()` with `f` make the error go away.

Thanks for reporting!

**Comment by davidson16807** [comment]
Np, good to hear there is support for ASI. I was getting worried. :)

**Comment by gabejohnson** [comment]
Fixed in https://github.com/sweet-js/sweet.js/pull/641
