### ISSUE TITLE
`new foo.bar()` is not compiled correctly

### ISSUE THREAD

**Issue by jlongster** [sweet-js/sweet.js#592]
Without using any macros, sweet.js outputs the wrong code for this:

```js
const db = new sqlite.Database("foo")
```

The generated output is:

```js
const db_0 = new "foo";
```

**Comment by gabejohnson** [comment]
Also:
```js
new a['b']()
```
yields:
```js
new (["b"]());
```
and

```js
new a.b()
```
throws `unexpected end of input`

**Comment by tamizhan** [comment]
I have a related question. Why is the compiler touching/rewriting non macro code ? Shouldn't it just expand just the macros and leave the remaining code untouched ?

**Comment by jlongster** [comment]
@tamizhan How does it know which code is macro or "non macro" code?

**Comment by tamizhan** [comment]
Syntax macros are explicitly defined. When the AST is traversed, can't the macro definitions be checked for a transformation ? Babel transformation plugins only change specific keywords they are targeting.

**Comment by jlongster** [comment]
Just to get you to think through this some more, how would that work if I made a `new` macro that should be invoked on the `new` keyword?

**Comment by gabejohnson** [comment]
@tamizhan but Babel _does_ parse everything to an AST, not just the targeted features. It's the same with sweet.js

The transforms happen as a token stream becomes an AST. So there's no being selective about it.
