### ISSUE TITLE
Precedence issue with ternary

### ISSUE THREAD

**Issue by disnet** [sweet-js/sweet.js#594]
``` js
x || y ? tru : fls
```

is being parsed as:

``` js
x || (y ? tru : fls)
```

but it should be:

``` js
(x || y) ? tru : fls
```

**Comment by gabejohnson** [comment]
Where are you seeing this? I can seem to reproduce it.

**Comment by disnet** [comment]
I can't repro either. Must have been fixed already.

**Comment by are1000** [comment]
I have a similiar issue:

    ctx.globalAlpha = lines.length === j + 1 ? this.cycle / this.maxCycle : 1

is being parsed as:

    ctx_16.globalAlpha = lines_18.length === (j + 1 ? this.cycle / this.maxCycle : 1);

but it should be:

    ctx_16.globalAlpha = (lines_18.length === j + 1) ? this.cycle / this.maxCycle : 1;
