### ISSUE TITLE
Missing statement in output

### ISSUE THREAD

**Issue by jlongster** [sweet-js/sweet.js#600]
A funny edge case:

``` js
if(true) {
  foo.bar("f")
  x = y
}
```

The output of this file is:

``` js
if (true) {
  x = y;
}
```

The `foo.bar` is gone. It seems to only happen with a member lookup. Unfortunately for me, it was a `console.log` that was missing so it was quite confusing....

Actually, looks like this repros it:

``` js
if(true) {
  foo.bar
  x = y
}
```

**Comment by jlongster** [comment]
Oh, weird, all these edge cases repro:

```js
x
foo.bar
x = y
```

```js
foo.bar
x = y
```

```js
x
foo.bar()
x = y
```

```js
x
foo.bar("hi")
x = y
```

**Comment by gabejohnson** [comment]
Fixed in https://github.com/sweet-js/sweet.js/pull/641
