### ISSUE TITLE
add console to macro scope

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [sweet-js/sweet.js#603]
I can't use the console inside the macro expansion code, because it seems console variable is undefined;

How can I access it. It's impossible for me to debug my macro code because debugger does not seem to work either.

Thanks a lot

**Comment by disnet** [comment]
Yeah, that is annoying; we should definitely add `console` to the scope of macros.

In the meantime, I've gotten the node-inspector debugger to work inside of a macro before so it should work. Are you using `debugger` statements?

Another hacky way to debug is to use `throw` statements.

**Comment by GuillaumeLeclerc** [comment]
I use node --inscpect path/to/sjs myfil.js

**Comment by gabejohnson** [comment]
@disnet I think there are a few other global properties we should add. Are there any in particular you are wary of?
