### ISSUE TITLE
Extraneous comas in modified example

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [sweet-js/sweet.js#605]
Hello,

I just modified a simple example and i have an invalid result:

``` javascript

syntax m = ctx => {
  let delim = ctx.next().value;
  var arr = [];
  for (let item of delim.inner()) {
    arr.push(item);
    arr.push(item);
  }
  return #`[${arr}]`;
}

m {
  1, 2, 3, "sdf"
}
```

output:

`[1, 1, , 2, 2, , 3, 3, , "sdf", "sdf"]`

**Comment by disnet** [comment]
You should be handling the `,` case in the loop right?

```js
syntax m = ctx => {
  let delim = ctx.next().value;
  var arr = [];
  for (let item of delim.inner()) {
    if (!item.isPunctuator(',')) {
        arr.push(item);
        arr.push(item);
    } else {
        arr.push(item);
    }
  }
  return #`[${arr}]`;
}
```

Unsurprising that adding `,` to the output twice will cause extra `,` right? :)

**Comment by gabejohnson** [comment]
@disnet I didn't expect the automatic comma insertion b/w items.

**Comment by disnet** [comment]
Ah, good point. Just realized that event without macros Sweet expands `[1 2 3]` as `[1, 2, 3]`. That would be a bug we need to fix.

**Comment by gabejohnson** [comment]
I think this might be an going on in `shift-codegen`. To fix it I think we'd have to extend the fortunately named `ExtensibleCodeGen`.
