### ISSUE TITLE
Impossible to create new syntax based on emojis

### ISSUE THREAD

**Issue by pirelenito** [sweet-js/sweet.js#607]
I'm a completely macro noob trying a crazy experiment of replacing JavaScript keywords with emojis. My first endeavor would to be replace `const` with `💎`.

So `💎 a = 1` would turn into `const a = 1`

This is the macro I'm [attempting](http://sweetjs.org/browser/editor.html#macro%20%F0%9F%92%8E%20=%20function%20%28ctx%29%20%7B%0A%20%20let%20ident%20=%20ctx.next%28%29.value;%0A%20%20ctx.next%28%29;%20//%20eat%20%60=%60%0A%20%20let%20init%20=%20ctx.expand%28%27expr%27%29.value;%0A%20%20return%20#%60const%20$%7Bident%7D%20=%20$%7Binit%7D%60;%0A%7D%0A%0A%F0%9F%92%8E%20Droid%20=%20%27BB-8%27;):

```
macro 💎 = function (ctx) {
  let ident = ctx.next().value;
  ctx.next(); // eat `=`
  let init = ctx.expand('expr').value;
  return #`const ${ident} = ${init}`;
}

💎 Droid = 'BB-8';
```

But it fails. 

If I **try a regular identifier** such as `whatever` it does work as you can check in the [online editor](http://sweetjs.org/browser/editor.html#syntax%20batata%20=%20function%20%28ctx%29%20%7B%0A%20%20let%20ident%20=%20ctx.next%28%29.value;%0A%20%20ctx.next%28%29;%20//%20eat%20%60=%60%0A%20%20let%20init%20=%20ctx.expand%28%27expr%27%29.value;%0A%20%20return%20#%60const%20$%7Bident%7D%20=%20$%7Binit%7D%60;%0A%7D%0A%0Abatata%20Droid%20=%20%27BB-8%27;)

I got here by first asking a question in the gitter channel

**Comment by gabejohnson** [comment]
Start of relevant conversation https://gitter.im/sweet-js/sweet.js?at=57f400fe43b5aeb00998bbb2

**Comment by gabejohnson** [comment]
The reason this fails is because 💎 isn't a valid identifier. This particular use case (aliasing keywords) could be accommodated using reader macros when they land.

**Comment by disnet** [comment]
This should be enabled as soon as we finish #687.
