### ISSUE TITLE
Document TypeScript mode

### ISSUE THREAD

**Issue by darkf** [sweet-js/sweet.js#609]
From [this link](https://github.com/sweet-js/sweet.js/blob/master/browser/mode/javascript/typescript.html), it seems like Sweet.js supports a TypeScript mode, but this isn't referenced anywhere in the docs.

**Comment by darkf** [comment]
It doesn't seem like it even properly supports TypeScript (see #482), so sweet.js is rather useless for this right now. Nevermind then. :-/

**Comment by disnet** [comment]
Yes, TS support is planned but not implemented yet.
