### ISSUE TITLE
How to define custom infix operators?

### ISSUE THREAD

**Issue by dmitriz** [sweet-js/sweet.js#613]
Can I use Sweet e.g. to define a macro supporting `equals` operator (see https://github.com/fantasyland/fantasy-land#setoid) to be used as

```
a equals b
```
instead of the bulkier JS native way
```
a.equals(b)
```

Motivation
---
Mathematically speaking (I am a professional mathematician),
the equivalence relation is fundamentally an **infix operator**,
which is unnatural to be attached as method to one of the sides,
especially when closely related infix operators like `==` are already part of the language.

**Comment by disnet** [comment]
This is on the roadmap. See #517.

**Comment by gabejohnson** [comment]
@disnet Can you reopen this? I'd prefer to keep a general design discussion about infix macros out #517.

**Comment by disnet** [comment]
@gabejohnson this request was for custom operators (the subject of #517) not infix macros.

**Comment by gabejohnson** [comment]
@disnet so it was. My mistake.
