### ISSUE TITLE
How should we handle reserved words?

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet.js#657]
While looking at #656 I realized we're not checking anywhere to see if a token is a reserved word.

@disnet Is that something you want to enforce? Or just punt to the environment the compiled code runs in?

**Comment by disnet** [comment]
We want to allow binding reserved keywords to macros but disallow normal runtime variable bindings.

**Comment by disnet** [comment]
I think this issue can be closed, we have a specific bug in #656 but otherwise reserved words are fine.
