### ISSUE TITLE
Have MacroContext::name return the correct type

### ISSUE THREAD

**Issue by disnet** [sweet-js/sweet.js#658]
As noticed in https://github.com/sweet-js/sweet.js/pull/644#issuecomment-289062888

**Comment by gabejohnson** [comment]
Should we just wrap the `Syntax` on the way out? We can always fix it for real when we finally get rid of `Syntax`.

**Comment by disnet** [comment]
Yes

**Comment by gabejohnson** [comment]
Do you want me to take this?
